version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: prestabanco
    ports:
      - 33060:3306

  app1:
    container_name: proyecto_prestabanco1
    image: motihc/proyecto_prestabanco
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/prestabanco?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=user
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
